name: UpdateProjectJSON
on:
  pull_request:
    types:
      - ready_for_review
  schedule:
    - cron: '47 * * * *'
  workflow_dispatch:

jobs:
  UpdateProjectJSON:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Get new project data as JSON, push to repo
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ORGANIZATION: osu-mercury-robotics
          PROJECT_NUMBER: 1
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectNext(number: $number) {
                  items(first: 100) {
                    nodes {
                      title
                      id
                      fieldValues(first: 20) {
                        nodes {
                          value
                          projectField {name}
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > ./assets/project_data.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated JSON"
          git push
